/// Writes every one-tap look's 4x5 colour matrix to `build/filters.json`, for
/// the website's filter-gallery generator (`tool/gen_filters.py`).
///
/// The point is that the site shows the app's OWN transforms: the previews are
/// generated by applying these exact numbers, so a tweak to `ColorMatrix.filter`
/// can never silently leave the marketing images showing a different look.
///
/// Run as a test, because `color_matrix.dart` reaches `dart:ui` through
/// `ImageAdjustments` and so needs the Flutter VM, not the plain Dart one:
///
///     flutter test tool/dump_filters.dart
library;

import 'dart:convert';
import 'dart:io';

import 'package:chromis/core/models/photo_filter.dart';
import 'package:chromis/core/rendering/color_matrix.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('dump filter matrices', () {
    final out = {
      'filters': [
        for (final f in PhotoFilter.values)
          {'name': f.name, 'label': f.label, 'matrix': ColorMatrix.filter(f)},
      ],
      // The tonal half of HDR. The texture half (local contrast) is painted,
      // not a matrix, so gen_filters.py approximates it the way the app does.
      'hdrTone': ColorMatrix.hdrTone(0.7),
    };
    Directory('build').createSync(recursive: true);
    File(
      'build/filters.json',
    ).writeAsStringSync(const JsonEncoder.withIndent('  ').convert(out));
  });
}
